# Generated by Django 6.0.6 on 2026-06-18 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.URLField(verbose_name='URL')),
                ('check_interval', models.PositiveIntegerField(default=60, help_text='Interval in seconds between checks', verbose_name='check interval')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monitored website',
                'verbose_name_plural': 'monitored websites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='status code')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='response time (ms)')),
                ('is_up', models.BooleanField(verbose_name='is up')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='checked at')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.monitoredwebsite')),
            ],
            options={
                'verbose_name': 'uptime check',
                'verbose_name_plural': 'uptime checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['website', '-checked_at'], name='monitoring__website_1886a4_idx')],
            },
        ),
    ]
