# Generated by Django 6.0.6 on 2026-06-23 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=10)),
                ('bucket_start', models.DateTimeField()),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('up_checks', models.PositiveIntegerField(default=0)),
                ('uptime_percentage', models.FloatField(default=0.0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('min_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_checks', to='monitoring.monitoredwebsite')),
            ],
            options={
                'verbose_name': 'aggregated check',
                'verbose_name_plural': 'aggregated checks',
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['website', 'resolution', '-bucket_start'], name='monitoring__website_8516ae_idx')],
                'unique_together': {('website', 'resolution', 'bucket_start')},
            },
        ),
    ]
