# Generated by Django 6.0.6 on 2026-06-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_aggregatedcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredwebsite',
            name='check_interval',
        ),
    ]
