# Generated by Django 6.0.6 on 2026-06-23 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_monitoredwebsite_check_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, verbose_name='hostname')),
                ('is_valid', models.BooleanField(verbose_name='is valid')),
                ('issuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='issuer')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('days_remaining', models.IntegerField(blank=True, null=True, verbose_name='days remaining')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='checked at')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to='monitoring.monitoredwebsite')),
            ],
            options={
                'verbose_name': 'SSL check',
                'verbose_name_plural': 'SSL checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['website', '-checked_at'], name='monitoring__website_e4f324_idx')],
            },
        ),
    ]
